### PR TITLE
add shadow text property

### PR DESCRIPTION
**Pull request by sammy-SC**
Adding drop shadow.

I couldn't find anything in the design.
## With drop shadow

simulator screen shot may 24 2016 17 05 48
## Without drop shadow

simulator screen shot may 24 2016 17 06 06

### CODE REVIEW

**Comment by sammy-SC** [comment]
we can alter shadow offset (default is [-1, 0], top shadow)

**Comment by famanson** [comment]
@sammy-SC could you give me an example screenshot with some properly bright background?

**Comment by sammy-SC** [comment]
here is a whiter one.

simulator screen shot may 24 2016 17 54 41

**Comment by famanson** [comment]
@sammy-SC actually I just reviewed the design, it's a gradient layer, not just a text shadow :(

**Pull request closed without merging**
